- hosts: live
  become: yes
  vars_files:
    - vars.yml
  roles:
    - role: 01-system-prep
- hosts: chroot
  gather_facts: no
  become: yes
  tasks:
    - name: make sure python is installed in our chroot
      raw: "apt-get update && apt-get -y install python"
- hosts: chroot
  become: yes
  vars_files:
    - vars.yml
  roles:
    - role: 02-chroot
    - role: 03-post-setup
